<?php
/**
 * OnePica_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OnePica
 * @package    OnePica_AvaTax
 * @author     OnePica Codemaster <codemaster@onepica.com>
 * @copyright  Copyright (c) 2009 One Pica, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php /** @var OnePica_AvaTax_Block_Adminhtml_Notification_Toolbar $this */?>
<?php if ($this->isEnabled()):?>
    <?php $count = $this->getQueuePendingRetryCount();?>
    <?php if ($count):?>
        <div class="notification-global">
            <?php if ($this->isAllowed()):?>
            <span class="f-right">
                <?php echo $this->__('Go to the <a href="%s">AvaTax Order Sync Queue</a>', $this->getQueueGridUrl());?>
            </span>
            <?php endif;?>
            <strong class="label"><?php echo $this->__('AvaTax:');?></strong>
            <?php if ($count == 1):?>
                <?php echo $this->__('There is <strong>%s</strong> entry in the AvaTax Order Sync Queue that has errored. Syncing is attemped %s times before permanently failing.', $count, $this->getQueueAttemptMaxValue());?>
            <?php else:?>
                <?php echo $this->__('There are <strong>%s</strong> entries in the AvaTax Order Sync Queue that have errored. Syncing is attemped %s times before permanently failing.', $count, $this->getQueueAttemptMaxValue());?>
            <?php endif;?>
        </div>
    <?php endif;?>
<?php endif;?>
