<?php
/**
 * OnePica_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OnePica
 * @package    OnePica_AvaTax
 * @author     OnePica Codemaster <codemaster@onepica.com>
 * @copyright  Copyright (c) 2009 One Pica, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \OnePica_AvaTax_Block_Adminhtml_Product_Edit_Tab_Avatax $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->getHeadText(); ?></h4>
    </div>

    <fieldset>

        <legend><?php echo Mage::helper('catalog')->__('Landed Cost') ?></legend>
        <table cellspacing="0" class="form-list" id="table_landedcost">
            <tr>
            </tr>
            <tr>
                <td class="label"><label for="landedcost_unit_of_weight"><?php echo Mage::helper('catalog')->__('Unit Of Weight') ?></label></td>
                <td class="value"><select id="landedcost_unit_of_weight" name="<?php echo $this->getFieldSuffix() ?>[landedcost_data][unit_of_weight]" class="select" <?php echo $_readonly;?>>
                        <?php foreach ($this->getUnitOfWeightOption() as $option): ?>
                            <?php $_selected = ($option['value'] == $this->getFieldValue('is_in_stock')) ? 'selected="selected"' : '' ?>
                            <option value="<?php echo $option['value'] ?>" <?php echo $_selected ?>><?php echo $option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="value scope-label"><?php echo Mage::helper('adminhtml')->__('[GLOBAL]') ?></td>
            </tr>
        </table>
    </fieldset>

</div>
