<?php
/**
 * OnePica_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OnePica
 * @package    OnePica_AvaTax
 * @author     OnePica Codemaster <codemaster@onepica.com>
 * @copyright  Copyright (c) 2009 One Pica, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml(); ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml(); ?></td>
        </tr>
    </table>
</div>

<?php $event = $this->getCurrentEvent();?>
<div class="entry-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Request'); ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <textarea readonly style="width:100%; height:300px"><?php echo $this->escapeHtml(
                    $event->getRequest()
                ); ?></textarea>
        </div>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Response'); ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <textarea readonly style="width:100%; height:300px"><?php echo $this->escapeHtml(
                    $event->getResult()
                ); ?></textarea>
        </div>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Additional'); ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <textarea readonly style="width:100%; height:300px"><?php echo $this->escapeHtml(
                    $event->getAdditional()
                ); ?></textarea>
        </div>
    </div>
</div>
