<?php /** @var OnePica_AvaTaxAr2_Block_Popup_Form $this */ ?>

<div id="avatax_certcapture_form_container">
    <div class="field">
        <label for="customer_number" class="required"><?php echo $this->__('Customer number'); ?></label>
        <div class="input-box">
            <input type="text" value="" name="customer_number" id="customer_number"/>
        </div>
    </div>
    <div class="field">
        <label for="ship_zone" class="required"><?php echo $this->__('State'); ?></label>
        <div class="input-box">
            <input type="text" value="" name="ship_zone" id="ship_zone"/>
        </div>
    </div>

    <div id="avatax_certcapture_form_parent" style="display:none;"></div>

    <div class="buttons-set">
        <button class="button2">
            <span><?php echo $this->__('Cancel'); ?></span>
        </button>

        <button class="button" id="avatax_certcapture_gencert2_button"
                onclick="AvaTaxCert.initApi('<?php echo $this->getToken() ?>');">
            <span><?php echo $this->__('Next step'); ?></span>
        </button>
    </div>
</div>
