<?php
/**
 * OnePica_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OnePica
 * @package    OnePica_AvaTax
 * @author     OnePica Codemaster <codemaster@onepica.com>
 * @copyright  Copyright (c) 2009 One Pica, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \OnePica_AvaTax_Block_Adminhtml_Order_View_Tab_Avatax $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->getHeadText(); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <?php echo $this->getExportButtonHtml() ?>
    </div>
</div>
