<?php /** @var OnePica_AvaTaxAr2_Block_ActionButton $this */ ?>
<?php if ($this->isEnabled()): ?>
    <div class="avatax-certcapture-button">
        <button class="button2" id="avatax_certcapture_gencert2_button"
                onclick="AvaTaxCert.initApi('<?php echo $this->getToken() ?>', '<?php echo $this->getShipZone() ?>');">
           <span><?php echo $this->__('Is this purchase tax-exempt?'); ?></span>
        </button>
        <div id="avatax_certcapture_form_container">
            <div id="avatax_certcapture_form_parent" style="display:none;"></div>
        </div>
    </div>
<?php endif; ?>
