<?php /** @var \OnePica_AvaTaxAr2_Block_Head_Script $this */ ?>
<?php if ($this->isEnabled()): ?>
    <script src="https://app.certcapture.com/gencert2/js"></script>
    <script src="<?php echo Mage::getBaseUrl() ?>/js/avatax/certcapture.js"></script>
    <script src="<?php echo Mage::getBaseUrl() ?>/js/prototype/window.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl() ?>/js/prototype/windows/themes/default.css" media="all">
    <style>
        #avatax_certcapture_table_content.dialog_content {
            background-color: #fff;
        }
    </style>
<?php endif; ?>
