<?php /** @var OnePica_AvaTaxAr2_Block_Total_Button $this */ ?>

<tr class="a-right">
    <td colspan="4">
        <button class="button2" id="avatax_certcapture_gencert2_button"
                onclick="AvaTaxCert.showPopup('<?php echo $this->getPopupUrl() ?>', '<?php
                echo $this->__('Create Exempt Certificate') ?>');">
            <span><?php echo $this->__('Is this purchase tax-exempt?'); ?></span>
        </button>
    </td>
</tr>
